---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: archive-results
spec:
  workspaces:
  - name: workspace
  inputs:
    params:
    - name: REPORTS_REPO_HOST
      description: The reports repository host based on https://github.com/chmouel/openshift-django-uploader
      default: http://reports-repo:8080
    - name: REPORTS_REPO_USERNAME
      description: The reports repository username
      default: reports
    - name: REPORTS_REPO_PASSWORD
      description: The reports repository password
      default: reports
    - name: RESULTS_DIR
      description: The directory to upload to reports repository
  steps:
    - name: upload
      workingDir: $(workspaces.workspace.path)
      image: docker.io/centos:8
      env:
        - name: PIPELINERUN_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tekton.dev/pipelineRun']
      script: |
        #!/usr/bin/env bash

        for f in $(find $(workspaces.workspace.path)/${inputs.params.RESULTS_DIR} -type f); do
          curl -u $(inputs.params.REPORTS_REPO_USERNAME):$(inputs.params.REPORTS_REPO_PASSWORD) -F path=$PIPELINERUN_NAME${f} -X POST -F file=@${f} $(inputs.params.REPORTS_REPO_HOST)/upload; echo ""
        done
  volumes:
    - name: maven-settings
      configMap:
        name: $(inputs.params.MAVEN_SETTINGS_CONFIGMAP)