apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gatling
spec:
  workspaces:
  - name: workspace
  params:
  - name: DURATION
    description: The duration of running simulations
    type: string
    default: "30"
  - name: CONCURRENT_USERS
    description: The number of concurrent users
    type: string
    default: "10"
  - name: APP_URL
    description: The application under test url
    type: string
  - name: SIMULATIONS_DIR
    description: The location of gatling simulations
    type: string
    default: src/gatling
  - name: RESULTS_DIR
    description: The directory where simulation reports will be generated
    type: string
    default: output/gatling
  - name: SIMULATION_NAME
    description: The name of the gatling simulation to run
    type: string
  steps:
    - name: run-tests
      image: quay.io/siamaksade/gatling:latest
      env:
        - name: PIPELINERUN_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tekton.dev/pipelineRun']
      script: |
        #!/usr/bin/env bash

        export JAVA_OPTS="-DtestDuration=$(inputs.params.CONCURRENT_USERS) -DuserCount=$(inputs.params.DURATION) -Dserver=$(inputs.params.APP_URL)"
        /opt/gatling/bin/gatling.sh -rd "Performance Tests" -rf $(workspaces.workspace.path)/$(inputs.params.RESULTS_DIR) -sf $(workspaces.workspace.path)/$(inputs.params.SIMULATIONS_DIR) -s $(inputs.params.SIMULATION_NAME)