---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: petclinic-trigger-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: petclinic-deploy-dev-run-
      labels:
        tekton.dev/pipeline: petclinic-deploy-dev
    spec:
      pipelineRef:
        name: petclinic-deploy-dev
      params:
      - name: APP_SOURCE_GIT
        value: $(params.gitrepositoryurl)
      - name: APP_SOURCE_REVISION
        value: $(params.gitrevision)
      workspaces:
      - name: local-maven-repo
        persistentVolumeClaim:
          claimName: maven-repo-pvc
      - name: job-workspace
        emptyDir: {}