---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic-deploy-dev-pvc-RANDOM
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: petclinic-deploy-dev-run-RANDOM
spec:
  pipelineRef:
    name: petclinic-deploy-dev
  resources:
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc
  - name: job-workspace
    persistentVolumeClaim:
      claimName: petclinic-deploy-dev-pvc-RANDOM
