apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: petclinic-deploy-dev-run-
spec:
  pipelineRef:
    name: petclinic-deploy-dev
  resources:
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc
  - name: job-workspace
    emptyDir: {}