apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: petclinic-deploy-stage
spec:
  params:
    - name: IMAGE_TAG
      default: latest
      type: string
      description: The image tag to be promoted from DEV to STAGE environment
    - name: APP_CONFIG_GIT
      type: string
      description: The application configuration git repository
      default: https://github.com/siamaksade/spring-petclinic-config
    - name: APP_CONFIG_REVISION
      type: string
      description: The application configuration git revision
      default: stage
  workspaces:
  - name: job-workspace
  tasks:
  - name: promote-stage
    taskRef:
      name: openshift-client
    params:
    - name: COMMANDS
      value: |
          oc tag demo-dev/spring-petclinic:$(params.IMAGE_TAG) demo-stage/spring-petclinic:$(params.IMAGE_TAG)
  - name: git-config
    taskRef:
      name: git-clone
    runAfter:
      - promote-stage
    workspaces:
    - name: src
      workspace: job-workspace
    params:
    - name: url
      value: $(params.APP_CONFIG_GIT)
    - name: revision
      value: $(params.APP_CONFIG_REVISION)
  - name: deploy-stage
    taskRef:
      name: oc-redeploy
    runAfter:
      - git-config
    workspaces:
    - name: workspace
      workspace: job-workspace
    params:
    - name: CONFIG_DIR
      value: src/spring-petclinic-config/app
    - name: DEPLOYMENT_NAME
      value: spring-petclinic
    - name: CONTAINER_NAME
      value: spring-petclinic
    - name: NAMESPACE
      value: demo-stage
    - name: IMAGE_URL
      value: image-registry.openshift-image-registry.svc:5000/demo-stage/spring-petclinic:$(params.IMAGE_TAG)
  - name: test
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-stage
    params:
    - name: COMMANDS
      value: |
          sleep $(($RANDOM % 20 + 10))
