apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: petclinic-deploy-dev
spec:
  params:
    - name: APP_SOURCE_GIT
      type: string
      description: The application git repository
      default: https://github.com/spring-projects/spring-petclinic
    - name: APP_SOURCE_REVISION
      type: string
      description: The application git revision
      default: master
    - name: APP_CONFIG_GIT
      type: string
      description: The application configuration git repository
      default: https://github.com/siamaksade/spring-petclinic-config
    - name: APP_CONFIG_REVISION
      type: string
      description: The application configuration git revision
      default: dev
    - name: APP_TESTS_GIT
      type: string
      description: The application test cases git repository
      default: https://github.com/siamaksade/spring-petclinic-gatling
  workspaces:
  - name: local-maven-repo
  - name: job-workspace
  tasks:
  - name: git-clone-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: job-workspace
    params:
    - name: url
      value: $(params.APP_SOURCE_GIT)
    - name: revision
      value: $(params.APP_SOURCE_REVISION)
    - name: depth
      value: "0"
    - name: subdirectory
      value: spring-petclinic
  - name: unit-tests
    taskRef:
      name: maven
    runAfter:
      - git-clone-source
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: workspace
      workspace: job-workspace
    params:
    - name: GOALS
      value: ["package"]
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
    - name: PROJECT_DIR
      value: spring-petclinic
  - name: release-app
    taskRef:
      name: maven
    runAfter:
      - unit-tests
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: workspace
      workspace: job-workspace
    params:
    - name: GOALS
      value:
      - deploy
      - -DskipTests=true
      - -DaltDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-releases/
      - -DaltSnapshotDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-snapshots/
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
    - name: PROJECT_DIR
      value: spring-petclinic
  - name: code-analysis
    taskRef:
      name: maven
    runAfter:
      - unit-tests
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: workspace
      workspace: job-workspace
    params:
    - name: GOALS
      value:
      - install
      - sonar:sonar
      - -Dsonar.host.url=http://sonarqube:9000
      - -Dsonar.userHome=/tmp/sonar
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
    - name: PROJECT_DIR
      value: spring-petclinic
  - name: gen-report
    taskRef:
      name: maven
    runAfter:
      - unit-tests
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: workspace
      workspace: job-workspace
    params:
    - name: GOALS
      value:
      - site
      - -DskipTests
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
    - name: PROJECT_DIR
      value: spring-petclinic
  - name: archive-report
    taskRef:
      name: archive-results
    runAfter:
      - gen-report
    workspaces:
    - name: workspace
      workspace: job-workspace
    params:
    - name: RESULTS_DIR
      value: spring-petclinic/target/site
  - name: build-image
    taskRef:
      name: s2i-java-11
    workspaces:
    - name: workspace
      workspace: job-workspace
    runAfter:
      - release-app
      - code-analysis
      - archive-report
    params:
      - name: TLSVERIFY
        value: "false"
      - name: MAVEN_MIRROR_URL
        value: http://nexus:8081/repository/maven-public/
      - name: PATH_CONTEXT
        value: spring-petclinic
      - name: OUTPUT_IMAGE
        value: image-registry.openshift-image-registry.svc:5000/demo-dev/spring-petclinic
  - name: git-clone-config
    taskRef:
      name: git-clone
    runAfter:
      - build-image
    workspaces:
    - name: src
      workspace: job-workspace
    params:
    - name: url
      value: $(params.APP_CONFIG_GIT)
    - name: revision
      value: $(params.APP_CONFIG_REVISION)
  - name: deploy
    taskRef:
      name: oc-redeploy
    runAfter:
      - git-clone-config
    workspaces:
    - name: workspace
      workspace: job-workspace
    params:
    - name: CONFIG_DIR
      value: spring-petclinic-config/app
    - name: DEPLOYMENT_NAME
      value: spring-petclinic
    - name: CONTAINER_NAME
      value: spring-petclinic
    - name: NAMESPACE
      value: demo-dev
    - name: IMAGE_URL
      value: image-registry.openshift-image-registry.svc:5000/demo-dev/spring-petclinic
  - name: git-tests
    taskRef:
      name: git-clone
    runAfter:
      - deploy
    workspaces:
    - name: src
      workspace: job-workspace
    params:
    - name: url
      value: $(params.APP_TESTS_GIT)
  - name: int-test
    taskRef:
      name: maven
    runAfter:
      - git-tests
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: workspace
      workspace: job-workspace
    params:
    - name: GOALS
      value: ["verify"]
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
    - name: PROJECT_DIR
      value: spring-petclinic
  - name: perf-test
    taskRef:
      name: gatling
    runAfter:
      - git-tests
    params:
      - name: APP_URL
        value: "http://spring-petclinic.demo-dev.svc.cluster.local:8080"
      - name: SIMULATIONS_DIR
        value: spring-petclinic-gatling
      - name: SIMULATION_NAME
        value: AddVisitSimulation
      - name: RESULTS_DIR
        value: output/gatling
  - name: archive-test-result
    taskRef:
      name: archive-results
    runAfter:
      - perf-test
      - int-test
    workspaces:
    - name: workspace
      workspace: job-workspace
    params:
    - name: RESULTS_DIR
      value: output/gatling